[control_node]
10.0.10.17	ansible_user=root

[k3s_cluster]
k3s-pve2 ansible_host=10.0.20.21 k3s_node_index=1
k3s-pve3 ansible_host=10.0.20.22 k3s_node_index=2
k3s-pve4 ansible_host=10.0.20.23 k3s_node_index=3

[k3s_cluster:vars]
ansible_user=rich
