---
# Essential system packages
automation_control_essential_packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - git
  - unzip
  - jq
  - sqlite3

# Terraform configuration
automation_control_terraform_repo_url: "https://apt.releases.hashicorp.com"
automation_control_terraform_gpg_url: "https://apt.releases.hashicorp.com/gpg"

# Semaphore dynamic downloader
automation_control_semaphore_api_url: "https://api.github.com/repos/semaphoreui/semaphore/releases/latest"
# Semaphore user
automation_control_semaphore_user: "rich"
automation_control_semaphore_email: "rpearsall1982@gmail.com"
