---
# Packages to install
nas_packages:
  - samba
  - samba-common-bin
  - nfs-kernel-server
  - zfsutils-linux
  - python3-boto3
# ZFS Configuration
nas_pool_name: "storage_pool"
nas_mount_point_base: "/mnt/storage"

zfs_raidz2_disks:
  - /dev/disk/by-id/ata-WDC_WD10JPVX-75JC3T0_WXK1E63ZHKV7
  - /dev/disk/by-id/ata-TOSHIBA_MQ01ABD100_37JOPUHTT
  - /dev/disk/by-id/ata-ST1000LM024_HN-M101MBB_S32XJ9GGC10989
  - /dev/disk/by-id/ata-TOSHIBA_MQ01ABD100_Y4MLP8TYT
  - /dev/disk/by-id/ata-TOSHIBA_MQ01ABD100_Y6SGCKJFT
  - /dev/disk/by-id/ata-TOSHIBA_MQ01ABD100_865XTG96T

# Grouping datasets with their optimized properties 
# Note: minio and seafile are marked as local_only: true so NFS skips them
nas_datasets:
  - name: "seafile"
    recordsize: "128k"
    local_only: true
  - name: "photoprism"
    recordsize: "128k"
  - name: "minio"
    recordsize: "128k"
    local_only: true
  - name: "pbs-backups"
    recordsize: "1m"
  - name: "pve1-backups"
    recordsize: "1m"
  - name: "k3s-backups"
    recordsize: "1m"
  - name: "jellyfin"
    recordsize: "1m"
    exports:
      - subnet: "10.0.10.0/24"
        options: "rw,async,no_subtree_check,no_root_squash"
      - subnet: "10.0.30.0/24"
        options: "rw,sync,no_subtree_check,insecure"
  - name: "jellyfin/dvds"
    recordsize: "1m"
    exports:
      - subnet: "10.0.10.0/24"
        options: "rw,async,no_subtree_check,no_root_squash"
      - subnet: "10.0.30.0/24"
        options: "rw,sync,no_subtree_check,insecure"
  - name: "jellyfin/music"
    recordsize: "256k"
    exports:
      - subnet: "10.0.10.0/24"
        options: "rw,async,no_subtree_check,no_root_squash"
      - subnet: "10.0.30.0/24"
        options: "rw,sync,no_subtree_check,insecure"

# MinIO Configuration
minio_download_url: "https://dl.min.io/server/minio/release/linux-amd64/minio"
minio_version: "RELEASE.2026-07-03T16-39-21Z"
minio_user: "minio"
minio_group: "minio"
