---
- name: Execute NAS Setup with Privilege Escalation
  block:
    - name: Update system and install NAS packages
      include_tasks: packages.yml

    - name: Configure ZFS Storage
      include_tasks: zfs.yml
  become: true
