---
- name: Execute NAS Setup with Privilege Escalation
  block:
    - name: Update system and install NAS packages
      include_tasks: packages.yml

    - name: Configure ZFS Storage
      include_tasks: zfs.yml

    - name: Configure NFS Exports
      include_tasks: file_share.yml

    - name: Deploy Standalone MinIO Backend
      include_tasks: minio.yml
  become: true
