---
- name: Check if K3s agent/server is already initialized on worker
  stat:
    path: /usr/local/bin/k3s
  register: k3s_agent_bin

- name: Joint Cluster Sequence for Peer Control Plane Nodes
  shell: >
    curl -sfL https://get.k3s.io | 
    INSTALL_K3S_VERSION="{{ k3s_version }}" sh -s - server 
    --server "https://{{ k3s_api_server }}:{{ k3s_api_port }}" 
    --token "{{ vault_k3s_cluster_token }}"
    --flannel-backend=none 
    --disable traefik
  when: not k3s_agent_bin.stat.exists

- name: Ensure secondary k3s service engines are verified running
  systemd:
    name: k3s
    state: started
    enabled: true
