---
- name: Check whether the default local-path StorageClass already exists
  kubernetes.core.k8s_info:
    kind: StorageClass
    name: local-path
  register: k3s_cluster_local_path_sc
  failed_when: false

- name: Delete default local-path StorageClass
  kubernetes.core.k8s:
    state: absent
    kind: StorageClass
    name: local-path
  when: k3s_cluster_local_path_sc.resources | length > 0

- name: Apply retained StorageClass
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: storage.k8s.io/v1
      kind: StorageClass
      metadata:
        name: local-path
        annotations:
          storageclass.kubernetes.io/is-default-class: "true"
      provisioner: rancher.io/local-path
      volumeBindingMode: WaitForFirstConsumer
      reclaimPolicy: Retain
