---
- name: Delete default local-path StorageClass
  kubernetes.core.k8s:
    state: absent
    kind: StorageClass
    name: local-path
  ignore_errors: true

- name: Apply retained StorageClass
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: storage.k8s.io/v1
      kind: StorageClass
      metadata:
        name: local-path
        annotations:
          storageclass.kubernetes.io/is-default-class: "true"
      provisioner: rancher.io/local-path
      volumeBindingMode: WaitForFirstConsumer
      reclaimPolicy: Retain
